name: InfraScale CI/CD

on:
  push:
    branches: [ main ]

jobs:

  test:

    runs-on: ubuntu-latest

    env:
      MONGO_URI: ${{ secrets.MONGO_URI }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Run Tests
        run: |
          cd backend
          npm test

  docker-build:

    runs-on: ubuntu-latest
    needs: test

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Containers
        run: docker compose build
